name: daleel
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  carousel_slider: ^5.1.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: ^8.1.3 # State management library
  flutter_bloc: ^8.1.3
  
  cupertino_icons: ^1.0.8
  dio : ^5.2.1 # Sends HTTP requests to the google directions api for route information
  flutter_polyline_points: ^2.1.0 # Draws polylines on the map
  google_maps_flutter: ^2.3.0 # Displays the map
  flutter_svg: ^2.2.0
  intl: ^0.20.2
  shared_preferences: ^2.2.2
  location: ^8.0.1 # For getting user's current location

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true



  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/